### ISSUE TITLE
Block Tags not generating after updating Moonlight Lib post v2.16.16

### ISSUE THREAD

**Issue by nostradica** [RasaNovum/Via_Romana#94]
You can't tap the sign after restarting or updating, but the path works because I can run fast, but teleporting with the sign doesn't work.

Impossible de toucher le panneau après un redémarrage ou une mise à jour, mais le chemin fonctionne car je peux courir vite ; par contre, la téléportation via le panneau ne fonctionne pas.
 

thx Nostradica

**Comment by xameryn** [comment]
Can I get some more information like mod/Minecraft version?

**Comment by nostradica** [comment]
after updating server and "Moonlight Lib" (from version 2.16.15 to version 2.16.18 or later).

**Comment by xameryn** [comment]
Ah yep confirmed on my end to be an issue with the new Moonlight Lib update, thanks. Will keep open until I fix on my end. It's working last (I think) on 2.16.16.

**Comment by Davwyn** [comment]
Good catch! I was going to attempt a workaround by making a datapack to manually create #path tags to see if that worked but it seems you already found the root of the problem.

Looking forward to the patch whenever you can get to it.

Cheers!

**Comment by xameryn** [comment]
Me and the Moonlight Lib dev found the issue and it should be fixed in the next update on their end (so v2.12.21+) 🫡

**Comment by xameryn** [comment]
The [new update](https://modrinth.com/mod/moonlight/version/1.20-2.16.21-fabric) fixes it 👍

**Comment by Bahanos** [comment]
Thx ^^

**Comment by ChessPanton** [comment]
> The [new update](https://modrinth.com/mod/moonlight/version/1.20-2.16.21-fabric) fixes it 👍

Is there a Minecraft 1.21.1 compatible version that fixes this issue? I tried it out using Moonlight Lib version 1.21-2.29.11 and the issue persists.

**Comment by xameryn** [comment]
@ChessPanton really weird, I couldn't recreate the issue in the first place with 1.21.1, I'll see if it's occurring on my end now.
